CREATE OR REPLACE VIEW VW_SALES_DATA AS
SELECT
    YEAR(O.O_ORDERDATE) AS ORDER_YEAR,    
    R.R_NAME AS REGION_NAME,
    N.N_NAME AS COUNTRY_NAME,
    P.P_MFGR AS PART_MFG,
    SUM(L.L_EXTENDEDPRICE) AS TOTAL_SALES
FROM
    SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS as o
JOIN
    SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER AS c
ON
    o.O_CUSTKEY = c.C_CUSTKEY
JOIN
    SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION as N
ON
    C.C_NATIONKEY = N.N_NATIONKEY
JOIN
    SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION as R
ON
    N.N_REGIONKEY=R.R_REGIONKEY    
JOIN
    SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM AS L
ON
    O.O_ORDERKEY = L.L_ORDERKEY
JOIN
    SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART AS P
ON
    L.L_PARTKEY = P.P_PARTKEY
GROUP BY
    GROUPING SETS(
        (YEAR(O.O_ORDERDATE),R.R_NAME,N_NAME,P.P_MFGR),
        (YEAR(O.O_ORDERDATE),R.R_NAME,P.P_MFGR) 
    );   