/*CREATE NEW ROLES*/
USE ROLE SECURITYADMIN;
 
--SALES MANAGER
CREATE ROLE SALES_MGR;
GRANT ROLE SALES_MGR TO ROLE SYSADMIN;
 
--AMERICA/EUROPE SALES
CREATE ROLE AM_EU_SALES;
GRANT ROLE AM_EU_SALES TO ROLE SALES_MGR;
 
--NON AMERICA/EUROPE SALES
CREATE ROLE NON_AM_EU_SALES;
GRANT ROLE NON_AM_EU_SALES TO ROLE SALES_MGR;
 
--CHILD GRANT FOR ACCESS
CREATE ROLE SNOW_SALES;
GRANT ROLE SNOW_SALES TO ROLE AM_EU_SALES;
GRANT ROLE SNOW_SALES TO ROLE NON_AM_EU_SALES;

--GRANT PERMISSIONS
/*VWH*/
USE ROLE ACCOUNTADMIN;
GRANT USAGE ON WAREHOUSE ST_DEMO_XS_WH TO ROLE SNOW_SALES;
 
/*SALES DATA VIEW*/
USE ROLE ST_DEMO_ROLE; --> DATA OWNER ROLE
GRANT USAGE ON DATABASE STREAMLIT_DB TO ROLE SNOW_SALES;
GRANT USAGE ON SCHEMA STREAMLIT_DATA TO ROLE SNOW_SALES;
GRANT SELECT ON STREAMLIT_DB.STREAMLIT_DATA.VW_SALES_DATA TO ROLE SNOW_SALES;


USE ROLE SALES_MGR;
SELECT
    CURRENT_ROLE(),
    IS_ROLE_IN_SESSION('AM_EU_SALES'),
    IS_ROLE_IN_SESSION('NON_AM_EU_SALES');
 
USE ROLE AM_EU_SALES;
SELECT
    CURRENT_ROLE(),
    IS_ROLE_IN_SESSION('AM_EU_SALES'),
    IS_ROLE_IN_SESSION('NON_AM_EU_SALES');



/*CREATE ROW ACCESS POLICY*/
USE ROLE ST_DEMO_ROLE; --> TABLE OWNER
CREATE OR REPLACE ROW ACCESS POLICY REGION_SALES_ACCESS
    AS (REGION_NAME VARCHAR) RETURNS BOOLEAN -> 
    CASE
        WHEN IS_ROLE_IN_SESSION('AM_EU_SALES')
        AND REGION_NAME IN('AMERICA', 'EUROPE') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('NON_AM_EU_SALES')
        AND REGION_NAME NOT IN('AMERICA', 'EUROPE') THEN TRUE
        ELSE FALSE
    END;
     
/*APPLY TO VIEW*/
    ALTER VIEW VW_SALES_DATA
ADD
    ROW ACCESS POLICY
REGION_SALES_ACCESS ON(REGION_NAME);  


/*CREATE TEMP TABLE TO STORE RESULTS*/
USE ROLE ST_DEMO_ROLE;
CREATE OR REPLACE TEMPORARY TABLE TBL_ROLE_ACCESS(
    ROLE_NAME VARCHAR(100),
    ALLOWED_REGIONS VARCHAR(100)
);
GRANT INSERT ON TABLE TBL_ROLE_ACCESS TO ROLE SNOW_SALES;
 
 
/*RUN INSERT FOR EACH ROLE*/
USE ROLE AM_EU_SALES;
USE ROLE NON_AM_EU_SALES;
USE ROLE SALES_MGR;
USE ROLE ST_DEMO_ROLE;
 
INSERT INTO TBL_ROLE_ACCESS
SELECT DISTINCT CURRENT_ROLE(),
LISTAGG(DISTINCT REGION_NAME,',') WITHIN GROUP (ORDER BY REGION_NAME) AS ALLOWED_REGIONS
FROM VW_SALES_DATA;
 
/*SHOW ALLOWED REGIONS BY ROLE*/
SELECT * FROM TBL_ROLE_ACCESS;