/*CONNECT TO PROPER DB/SCHEMA/ROLE*/
USE ROLE ST_DEMO_ROLE;
USE SCHEMA STREAMLIT_DB.STREAMLIT_DATA;
USE WAREHOUSE ST_DEMO_XS_WH;

/*CREATE TABLE FOR ROLE STORAGE*/
CREATE OR REPLACE TABLE TBL_ROW_ACCESS(
    ROW_ID NUMBER(5,0)
        AUTOINCREMENT START WITH 1 INCREMENT BY 1
    ,ROLE_NAME VARCHAR(100)
    ,REGION_NAME VARCHAR(100)
);


/*DROP CURRENT ROW ACCESS POLICY*/
ALTER VIEW VW_SALES_DATA
    DROP ROW ACCESS POLICY
        REGION_SALES_ACCESS;

/*LOAD DATA TO TABLE BASED 
ON CURRENT ROW ACCESS POLICY*/
TRUNCATE TABLE TBL_ROW_ACCESS;

INSERT INTO TBL_ROW_ACCESS(REGION_NAME,ROLE_NAME)
WITH RG AS(
SELECT REGION_NAME FROM VW_SALES_DATA GROUP BY REGION_NAME
)
SELECT
REGION_NAME,
CASE
        WHEN  REGION_NAME IN('AMERICA', 'EUROPE') THEN 'AM_EU_SALES'
        WHEN REGION_NAME NOT IN('AMERICA', 'EUROPE') THEN 'NON_AM_EU_SALES'
        ELSE NULL
    END AS ROLE_NAME
FROM
    RG;

/*VERIFY ENTRY*/
SELECT * FROM TBL_ROW_ACCESS;


/*ALTER ROW ACCESS POLICY
TO USE TABLE*/
CREATE OR REPLACE ROW ACCESS POLICY REGION_SALES_ACCESS
    AS (REGION_NAME VARCHAR) RETURNS BOOLEAN -> 
    EXISTS(
        SELECT 1 FROM TBL_ROW_ACCESS AS RA
        WHERE IS_ROLE_IN_SESSION(RA.ROLE_NAME)
        AND RA.REGION_NAME = REGION_NAME);
    
/*APPLY TO VIEW*/
    ALTER VIEW VW_SALES_DATA
ADD
    ROW ACCESS POLICY
REGION_SALES_ACCESS ON(REGION_NAME);

/*CREATE TEMP TABLE
TO STORE RESULTS
*/
USE ROLE ST_DEMO_ROLE;
CREATE OR REPLACE TEMPORARY TABLE TBL_ROLE_ACCESS(
    ROLE_NAME VARCHAR(100),
    ALLOWED_REGIONS VARCHAR(100)
);
GRANT INSERT ON TABLE TBL_ROLE_ACCESS TO ROLE SNOW_SALES;


/*RUN INSERT FOR EACH ROLE*/
USE ROLE AM_EU_SALES;
USE ROLE NON_AM_EU_SALES;
USE ROLE SALES_MGR;
USE ROLE ST_DEMO_ROLE;

INSERT INTO TBL_ROLE_ACCESS
SELECT DISTINCT CURRENT_ROLE(),
LISTAGG(DISTINCT REGION_NAME,',') WITHIN GROUP (ORDER BY REGION_NAME) AS ALLOWED_REGIONS
FROM VW_SALES_DATA;

/*SHOW ALLOWED REGIONS BY ROLE*/
SELECT * FROM TBL_ROLE_ACCESS;



/*FIX STREAMLIT*/
USE ROLE ST_DEMO_ROLE;
USE SCHEMA STREAMLIT_DB.STREAMLIT_DATA;

INSERT INTO TBL_ROW_ACCESS
    (ROLE_NAME,REGION_NAME)
SELECT
    'ST_DEMO_ROLE' as ROLE_NAME
    ,REGION_NAME
FROM TBL_ROW_ACCESS;
