USE ROLE ST_DEMO_ROLE;
USE DATABASE ST_DEMO_DB;
USE WAREHOUSE ST_DEMO_XS_WH;

/*CREATE SCHEMA FOR EXTERNAL STAGES*/
CREATE OR REPLACE SCHEMA EXTERNAL_STAGES;

/*CREATE THE STAGE*/
CREATE OR REPLACE STAGE NOAA_S3
    URL = 's3://noaa-ghcn-pds/'
    DIRECTORY = (ENABLE=FALSE);

/*CREATE THE FILE FORMAT*/
CREATE OR REPLACE FILE FORMAT EXTERNAL_STAGES.NOAA_FIXED_WIDTH
    TYPE = CSV
    FIELD_DELIMITER = NONE /*NO DELIMITER ON A FIXED WIDTH*/
    ;
    
/*QUERY THE FILE DIRECTLY*/
SELECT
    $1
FROM
    @EXTERNAL_STAGES.NOAA_S3/ghcnd-stations.txt
    (FILE_FORMAT=>EXTERNAL_STAGES.NOAA_FIXED_WIDTH);


/*QUERY THE README DIRECTLY
FOR FILE FORMAT INFO*/
SELECT
    $1
FROM
    @EXTERNAL_STAGES.NOAA_S3/readme.txt
    (FILE_FORMAT=>EXTERNAL_STAGES.NOAA_FIXED_WIDTH)
OFFSET 424 ROWS FETCH NEXT 15;    


/*CREATE TARGET TABLE*/
CREATE OR REPLACE TRANSIENT TABLE RAW_DATA.NOAA_STATIONS(
    ID VARCHAR(11)
    ,LATITUDE FLOAT
    ,LONGITUDE FLOAT
    ,ELEVATION FLOAT
    ,STATE VARCHAR(2)
    ,NAME VARCHAR(30)
    ,GSN_FLAG VARCHAR(3)
    ,HCN_CRN_FLAG VARCHAR(3)
    ,WMO_ID VARCHAR(5)
);

/*TRUNCATE AND LOAD THE TABLE DIRECT*/
TRUNCATE TABLE RAW_DATA.NOAA_STATIONS;

/*LOAD THE DATA BY QUERYING THE FILE DIRECTLY*/
COPY INTO RAW_DATA.NOAA_STATIONS
FROM
(
    SELECT
        NULLIF(TRIM(SUBSTRING($1,1,11)),'')::VARCHAR AS ID
        ,NULLIF(TRIM(SUBSTRING($1,13,8)),'')::FLOAT AS LATITUDE
        ,NULLIF(TRIM(SUBSTRING($1,22,9)),'')::FLOAT AS LONGITUDE
        ,NULLIF(TRIM(SUBSTRING($1,32,6)),'')::FLOAT AS ELEVATION
        ,NULLIF(TRIM(SUBSTRING($1,39,2)),'')::VARCHAR AS STATE
        ,NULLIF(TRIM(SUBSTRING($1,42,30)),'')::VARCHAR AS NAME
        ,NULLIF(TRIM(SUBSTRING($1,73,3)),'')::VARCHAR AS GSN_FLAG
        ,NULLIF(TRIM(SUBSTRING($1,77,3)),'')::VARCHAR AS HCN_CRN_FLAG
        ,NULLIF(TRIM(SUBSTRING($1,81,6)),'')::VARCHAR AS WMO_ID
    FROM
        @EXTERNAL_STAGES.NOAA_S3/ghcnd-stations.txt
        (FILE_FORMAT=>EXTERNAL_STAGES.NOAA_FIXED_WIDTH)
);


/*REVIEW DATA LOAD*/
SELECT * FROM RAW_DATA.NOAA_STATIONS;

