/*GRANT STREAMLIT APP ROLE RIGHT TO CORTEX -- MUST BE DONE BY ACCOUNTADMIN*/
USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWFLAKE;
GRANT DATABASE ROLE CORTEX_USER to ROLE ST_DEMO_ROLE;

/*CHECK*/
USE ROLE ST_DEMO_ROLE;
USE WAREHOUSE STREAMLIT_XS_WH;
USE DATABASE STREAMLIT_DB;
USE SCHEMA STREAMLIT_DATA;

SELECT SNOWFLAKE.CORTEX.TRANSLATE('Hello! How are you?','en','de');

/*APP SETUP*/
/*CREATE SCHEMA AND STAGES*/
USE ROLE ST_DEMO_ROLE;
/*SWTICH DB AND WAREHOUSE*/
USE DATABASE STREAMLIT_DB;
USE WAREHOUSE STREAMLIT_XS_WH;
/*SWITCH TO SCHEMA*/
USE SCHEMA STREAMLIT_STAGES;
/*CREATE STAGE WITH DIRECTORY*/
CREATE STAGE STG_CORTEX
    DIRECTORY = (ENABLE=TRUE);
/*USE APPS SCHEMA*/
USE SCHEMA STREAMLIT_APPS;

/*CREATE STREAMLIT APP*/
CREATE STREAMLIT CORTEX_DEMO
    ROOT_LOCATION = '@STREAMLIT_DB.STREAMLIT_STAGES.STG_CORTEX'
    MAIN_FILE = 'Cortex_Demo.py'
    QUERY_WAREHOUSE = STREAMLIT_XS_WH
    COMMENT = 'Snowflake Cortex Demo';
	
/*GRANT PRIVILEGES TO APP USERS ROLE TO RUN APP*/
USE SCHEMA STREAMLIT_DB.STREAMLIT_APPS;
GRANT USAGE ON STREAMLIT CORTEX_DEMO TO ROLE ST_APP_USERS;