USE ROLE ACCOUNTADMIN;
ALTER USER DOMO_READER_SVC_01
    SET TYPE=SERVICE;
ALTER USER DOMO_READER_SVC_01
    SET NETWORK_POLICY = DOMO_INBOUND_NETWORK_POLICY;
ALTER USER DOMO_READER_SVC_01
    SET RSA_PUBLIC_KEY = 'ENTER PUBLIC KEY HERE';
	
USE ROLE ACCOUNTADMIN;
ALTER USER DOMO_WRITER_SVC_01
    SET TYPE=SERVICE;
ALTER USER DOMO_WRITER_SVC_01
    SET NETWORK_POLICY = DOMO_INBOUND_NETWORK_POLICY;
ALTER USER DOMO_WRITER_SVC_01
    SET RSA_PUBLIC_KEY = 'ENTER PUBLIC KEY HERE';
	
		